### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by olddonkey** [Junlau/ScrollViewInScrollView#1]
非常赞，看了你对卓同学的优化，有个小问题，这样的情况是有意为之的还是算是一个bug，附上一个gif

![gif5](https://cloud.githubusercontent.com/assets/22208754/25809083/a0c67af8-33d1-11e7-9312-09b28cb49692.gif)

**Comment by Junlau** [comment]
感谢提出问题，不好意思没有及时更新demo，刚才已修改了极端位置的动画方式，我测了一下，应该没什么大问题了

**Comment by olddonkey** [comment]
点赞，完美了
